final_society/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'E-House Care Admin Interface'
admin.site.site_title = 'E-House Care'
admin.site.intex_title = 'Database Management System'
urlpatterns = [
    path('admin1/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('sec.urls')),
]

sec/urls.py
from pydoc import resolve
from django.conf import settings
from django.urls import path
from main.views import *
from .import views 
app_name='sec'

urlpatterns = [

    path('hello', views.hello, name='hello'),

    path('', views.adminlogin, name='adminlogin'),
    path('ahome', views.ahome, name = 'ahome'),

    path('visitor', views.visitor, name='visitor'),
    path('addvisitor', views.addvisitor, name='addvisitor'),
    path('visitor/<int:v_id>/', views.delvisitor, name='delvisitor'),
    path('otpfunc/<int:vi_id>/', views.otpfunc, name='otpfunc'),

    path('residents', views.residents, name='residents'),
    path('register', views.register, name='register'),
    path('<int:del_id>/', views.deleteuser, name='deleteuser'),
    path('residents/<int:profile_id>/', views.showprof, name='showprof'),
    
    path('amakenotice/', views.amakenotice, name='amakenotice'),
    path('notices', views.notices, name='notices'),
    path('notices/n/<int:no_id>/', views.shownotice, name='shownotice'),
    path('notices/<int:n_id>/', views.delnotice, name='delnotice'),
    path('notices/editnotice/<int:edit_id>', views.editnotice, name='editnotice'),

    path('residents/bills/<int:p_id>/', views.showbill, name ='showbill'),
    path('residents/bills/view/<int:bill_id>/<int:p_id>/', views.billview, name ='billview'),
    path('residents/bills/del/<int:bill_id>/', views.billdelete, name ='billdelete'),
    path('residents/bills/create/<int:pr_id>/', views.createbill, name ='createbill'),
    path('residents/massbill', views.massbill, name='massbill'),
    path('allbills', views.allbills, name='allbills'),
    path('paidbills', views.paidbills, name='paidbills'),
    path('latebills', views.latebills, name='latebills'),
    path('duebills', views.duebills, name='duebills'),

    path('complaints/c/<int:co_id>/', views.deletecomplaint, name='deletecomplaint'),
    path('complaints/<int:c_id>/',views.opencomplaint, name='opencomplaint'),
    path('complaints', views.complaints, name='complaints'),
    path('complaints/resolve/<int:c_id>/', views.resolve, name='resolve')
     
]

sec/models.py
from django.db import models

# Create your models here.

sec/forms.py
from email.policy import default
from pyexpat import model
from django import forms
from django.forms import ModelForm
from main.models import Complaint, Notice, Service, Visitor, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime

class EditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name','email', 'age', 'flat_no', 'phone_number', 'status','photo']
    
    ch = (
        ("r", "Resident"),
        ("s", "Staff"),
        ("a", "Superuser")
    )
    name = forms.CharField()
    age = forms.IntegerField()
    email = forms.EmailField()
    flat_no = forms.CharField()
    photo = forms.ImageField(required=False)
    phone_number = forms.IntegerField()
    status = forms.ChoiceField(choices=ch, required=False)

class EditNoticeForm(ModelForm):
    class Meta:
        model = Notice
        fields = ['header_notice','details_notice', 'showflag']
    header_notice = forms.CharField(required=True)
    details_notice = forms.CharField(
        required=False,
        widget=forms.Textarea)
    ch = (("y", "Show"), ("n", "Hide"))    
    showflag = forms.ChoiceField(choices=ch)

class ResolveForm(ModelForm):
    class Meta:
        model = Complaint
        fields = ['resolve_msg']
    resolve_msg = forms.CharField(
        required=True,
        widget=forms.Textarea)

sec/views.py
from xml.parsers.expat import model
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from main.forms import NewUserForm, ComplaintForm, NoticeForm, ServiceForm, VisitorForm, BillForm, otpForm
from sec.forms import EditForm, EditNoticeForm, ResolveForm
from main.models import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMessage
from django.db.models import Sum
from django.db.models import F
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
import http.client
import random
from twilio.rest import Client
import pytz


def register(request):

    if request.method == "POST":
        form = NewUserForm(request.POST, request.FILES)


        if form.is_multipart():
            form.save()

            username1 = form.cleaned_data.get('username')
            name1 = form.cleaned_data.get('name')
            email1 = form.cleaned_data.get('email')
            age1 = form.cleaned_data.get('age')
            flat_no1 = form.cleaned_data.get('flat_no')
            phone_number1 = form.cleaned_data.get('phone_number')
            photo1 = form.cleaned_data.get('photo')
      
            new = User.objects.get(username = username1)
            
            passw = form.cleaned_data.get('password1')
            st =form.cleaned_data['status']
            subject = 'Your password for E-Housing Society'
            message = "Your username is: "+username1+'\n Your password is: '+passw
            from_email = settings.EMAIL_HOST_USER
            recievers = [email1]
            emailsending = EmailMessage(subject, message, from_email, recievers)
            emailsending.send()


            print(st)
            if st == 'r':
                newuser = Profile(user=new, email=email1, age=age1, flat_no=flat_no1, phone_number=phone_number1, name=name1, photo=photo1, status = st)
                newuser.save()
            if st == 's':
             
                newuser = Profile(user=new, email=email1, age=age1, flat_no=flat_no1, phone_number=phone_number1, name=name1, photo=photo1, status = st)

                newuser.save()
                us = User.objects.get(username = username1)
                us.is_staff= True
                us.save()
            if st == 'a':
             
                newuser = Profile(user=new, email=email1, age=age1, flat_no=flat_no1, phone_number=phone_number1, name=name1, photo=photo1, status = st)

                newuser.save()
                us = User.objects.get(username = username1)
                us.is_superuser= True
                us.save()  

            # newuser = Profile(user=new, email=email1, age=age1, flat_no=flat_no1, phone_number=phone_number1, name=name1, photo=photo1, status = st)
            # newuser.save()
            messages.success(request, f'New Account Created!: {username1}')
            return redirect("sec:ahome")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")
            
    form = NewUserForm
    return render(request, "sec/register.html", context={'form': form})


def adminlogin(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f'You are now logged in as {username}')
                return redirect('sec:ahome')
            else:
                messages.error(request, f'Invalid username or password')
        else:
            messages.error(request, f'Invalid username or password')

    form = AuthenticationForm()
    return render(request, "sec/login.html", {'form': form})

def hello(request):
    return HttpResponse('Hello!!')

def ahome(request):
    #for updating bills
    
    return render(request, 'sec/ahome.html')

def notices(request):
    return render(request, 'sec/notices.html',{'notice':Notice.objects.all()})

def delnotice(request, n_id):
    vi = get_object_or_404(Notice, pk = n_id)
    vi.delete()
    messages.info(request, 'Notice deleted successfully')
    return render(request, 'sec/ahome.html') 

def shownotice(request, no_id):
    notice =  get_object_or_404(Notice, pk = no_id)
    return render(request, 'sec/shownotice.html', {'notice':notice})

def amakenotice(request):
    note = Notice()
    if request.method == 'GET':
        return render(request, "sec/makenotice.html", context={'form': NoticeForm()})
    else:
        form = NoticeForm(request.POST)
        if form.is_valid():

            header_notice = form.cleaned_data['header_notice']
            details_notice = form.cleaned_data['details_notice']
        
            flag = 'y'
            dt = datetime.datetime.now()
            newnotice = Notice(header_notice = header_notice, details_notice=details_notice, publish_dt = dt, showflag = flag)
            
            subject = newnotice.header_notice
            message = newnotice.details_notice
            from_email = settings.EMAIL_HOST_USER
            recievers = []
            for user1 in Profile.objects.all():
                recievers.append(user1.email)
            emailsending = EmailMessage(subject, message, from_email, recievers)
            emailsending.send()

            newnotice.save()
            messages.success(request, 'Notice made successfully!')
            return redirect('sec:ahome')

def editnotice(request, edit_id):
    notice = get_object_or_404(Notice, pk = edit_id)
    if request.method == 'POST':
        form = EditNoticeForm(request.POST)
        if form.is_valid():
            notice.header_notice = form.cleaned_data['header_notice']
            notice.details_notice = form.cleaned_data['details_notice']
            notice.showflag = form.cleaned_data['showflag']
            notice.save()
            messages.success(request, 'Notice edited successfully!')
            return render(request, 'sec/ahome.html')
    else:
        return render(request, 'sec/editnotice.html', {'notice':notice, 'form':EditNoticeForm})

def residents(request):
 
    return render(request, 'sec/residents.html', {'prof':Profile.objects.all()})     

def showprof(request, profile_id):
    userprofile = get_object_or_404(Profile, pk = profile_id)
    if request.method == 'POST':
        form = EditForm(request.POST, request.FILES)
        if form.is_valid():
            for user in User.objects.all():
                if user.id == userprofile.user_id:
                    newuser = user
            userprofile.name = form.cleaned_data['name']
            userprofile.email = form.cleaned_data['email']
            userprofile.age = form.cleaned_data['age']
            userprofile.flat_no = form.cleaned_data['flat_no']
            userprofile.phone_number = form.cleaned_data['phone_number']
            if form.cleaned_data['photo'] is not None:
                userprofile.photo = form.cleaned_data['photo']
            
            st = form.cleaned_data['status']
            if st == 'r':
                userprofile.status = st
                userprofile.save()
            if st == 's':
                
                userprofile.status = st
                userprofile.save()
                us = User.objects.get(username = newuser.username )
                us.is_staff= True
                us.save()
            if st == 'a':
             
                userprofile.status = st
                userprofile.save()
                us = User.objects.get(username = newuser.username)
                us.is_superuser= True
                us.save()
            userprofile.save()
            messages.success(request, f'Changes made successfully!')
            return redirect('sec:ahome')
        
    else:
        
        return render(request, 'sec/edituser.html', {'userp': userprofile, 'form':EditForm, 'prof':Profile.objects.all()})

def deleteuser(request, del_id):
    userprof = get_object_or_404(Profile, pk = del_id)
    for user in User.objects.all():
        if user.id == userprof.user_id:
            deluser = user
    userprof.delete()
    deluser.delete()
    messages.success(request, 'User deleted successfully')
    return render(request, 'sec/ahome.html')


def visitor(request):
    messages.info(request, 'You are viewing the Visitor Log')
    return render(request, "sec/visitor.html", context={'visit': Visitor.objects.all})

def addvisitor(request):
    if request.method == 'GET':
        return render(request, "sec/addvisitor.html", context={'form': VisitorForm()})
    else:
        form = VisitorForm(request.POST)
        if form.is_valid():

            visitor_name = form.cleaned_data['visitor_name']
            visitor_phone = form.cleaned_data['visitor_phone']
            visiting_flat= form.cleaned_data['visiting_flat']
            visiting_date = form.cleaned_data['visiting_date']
            visiting_time = form.cleaned_data['visiting_time']
            

            vi = Visitor(visitor_name = visitor_name, visitor_phone= visitor_phone, visiting_flat=visiting_flat, visiting_date=visiting_date,
                visiting_time=visiting_time)
            # newvisitor.user = request.user
            phone_no = visitor_phone
            check_flat = Profile.objects.filter(flat_no = visiting_flat).first()
            if check_flat:
                print(' ')
            else:
                
                messages.error(request,'No such flat exists')
                return redirect('sec:ahome')
            
            global otp

sec/templates/sec/includes/messages.html
{% load static %}
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'toastr/toastr.min.css' %}" media="all">
<script type="text/javascript" src="{% static 'toastr/toastr.min.js' %}"></script> 
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success'%}
        <script type=text/javascript>toastr.{{message.tags}}('{{message}}')</script>
        {% elif message.tags == 'info'%}
            <script type=text/javascript>toastr.{{message.tags}}('{{message}}')</script>
        {% elif message.tags == 'warning'%}
        <script type=text/javascript>toastr.{{message.tags}}('{{message}}')</script>
        {% elif message.tags == 'error'%}

            <script type=text/javascript>toastr.{{message.tags}}('{{message}}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

sec/templates/sec/includes/nav.html
{% load static %}
<div
  id="spinner"
  class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center"
>
  <div
    class="spinner-border text-primary"
    style="width: 3rem; height: 3rem"
    role="status"
  >
    <span class="sr-only">Loading...</span>
  </div>
</div>
<!-- Spinner End -->
<div class="hidden" id="sidebar">
  <!-- Sidebar Start -->
  <div class="sidebar pe-4 pb-3 hidden" id="hidden">
    <nav class="navbar bg-light navbar-light">
      <a href="" class="navbar-brand mx-4 mb-3">
        <h6 class="text-primary">
          <img src="{% static 'images/logo.svg' %}" alt="" width="50" height="50">  Admin Interface
        </h6>
      </a>
      <div class="d-flex align-items-center ms-4 mb-4">
        <div class="position-relative">
          <img
            class="rounded-circle"
            src="/media/main/images/pfp.jpg"
            alt=""
            style="width: 40px; height: 40px"
          />
          <div
            class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"
          ></div>
        </div>
        <div class="ms-3">
          <h6 class="mb-0">{{user.username}}</h6>
          <span></span>
        </div>
      </div>
      <div class="navbar-nav w-100">
        <a href="/admin/ahome" class="nav-item nav-link active"
          ><i class="fa fa-tachometer-alt me-2"></i>Home</a
        >
        
        <a href="/admin/residents" class="nav-item nav-link"
          ><i class="fa fa-th me-2"></i>Residents</a
        >
        <a href="/admin/complaints" class="nav-item nav-link"
          ><i class="fa fa-file me-2"></i>Complaints</a
        >
        <a href="/admin/notices" class="nav-item nav-link"
          ><i class="fa fa-file me-2"></i>Notices</a
        >
        <a href="/admin/visitor" class="nav-item nav-link"
          ><i class="fa fa-table me-2"></i>Visitor Log</a
        >
        <a href="/admin/allbills" class="nav-item nav-link"
          ><i class="fa fa-table me-2"></i>Bills</a
        >
        <!-- <div class="nav-item dropdown">
          <a href="#" class="nav-item nav-link" 
            ><i class="fa fa-laptop me-2"></i>Services</a
          >
          <div class="dropdown-menu bg-transparent border-0">
            <a href="button.html" class="dropdown-item">Electrian</a>
            <a href="typography.html" class="dropdown-item">Plumber</a>
            <a href="element.html" class="dropdown-item">Carpenter</a>
          </div>
        </div> -->
        <!-- <a href="chart.html" class="nav-item nav-link"
          ><i class="fa fa-chart-bar me-2"></i>Expenses</a
        > -->
        <!-- <div class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"
            ><i class="far fa-file-alt me-2"></i>Pages</a
          >
          <div class="dropdown-menu bg-transparent border-0">
            <a href="signin.html" class="dropdown-item">Sign In</a>
            <a href="signup.html" class="dropdown-item">Sign Up</a>
            <a href="404.html" class="dropdown-item">404 Error</a>
            <a href="blank.html" class="dropdown-item">Blank Page</a>
          </div>
        </div> -->
      </div>
    </nav>
  </div>
  <!-- Sidebar End -->
</div>
<!-- Navbar Start -->
<nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
  <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
  </a>
  <a href="#" class="sidebar-toggler" >
    <i class="fa fa-bars"></i>
  </a>

  <div class="navbar-nav align-items-center ms-auto">
    <div class="nav-item dropdown">
      <a href="{% url 'sec:register' %}">
        <i class="fa fa-user me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Add User</span>
      </a>
      &nbsp &nbsp
      <a href="{% url 'sec:massbill' %}">
        <i class="fa fa-th me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Generate Mass Bill</span>
      </a>
      &nbsp &nbsp
      <a href="{% url 'sec:amakenotice' %}">
        <i class="fa fa-file-alt me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Post Notice</span>
      </a>
      <div class="bg-light border-0 rounded-0 rounded-bottom m-0"></div>
    </div>

    <div class="nav-item dropdown">
      <a href="{% url 'sec:addvisitor' %}" class="nav-link -toggle">
        <i class="fa fa-plus me-lg-2"></i>
        <span class="d-none d-lg-inline-flex">Add Visitor</span>
      </a>
      <div
        class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0"
      ></div>
    </div>
    <div class="nav-item dropdown">
      <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
        <i class="fa fa-laptop"><span>&#9881;</span></i>
        
        <span class="d-none d-lg-inline-flex">Settings</span>
      </a>
      <div
        class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0"
      >
        <!-- <a href="#" class="dropdown-item">My Profile</a> -->
        <a href="/logout" class="dropdown-item">Log Out</a>
      </div>
    </div>
  </div>
</nav>
<!-- Navbar End -->