final_society/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'E-House Care Admin Interface'
admin.site.site_title = 'E-House Care'
admin.site.intex_title = 'Database Management System'
urlpatterns = [
    path('admin1/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('sec.urls')),
]

sec/urls.py
from pydoc import resolve
from django.conf import settings
from django.urls import path
from main.views import *
from .import views 
app_name='sec'

urlpatterns = [

    path('hello', views.hello, name='hello'),

    path('', views.adminlogin, name='adminlogin'),
    path('ahome', views.ahome, name = 'ahome'),

    path('visitor', views.visitor, name='visitor'),
    path('addvisitor', views.addvisitor, name='addvisitor'),
    path('visitor/<int:v_id>/', views.delvisitor, name='delvisitor'),
    path('otpfunc/<int:vi_id>/', views.otpfunc, name='otpfunc'),

    path('residents', views.residents, name='residents'),
    path('register', views.register, name='register'),
    path('<int:del_id>/', views.deleteuser, name='deleteuser'),
    path('residents/<int:profile_id>/', views.showprof, name='showprof'),
    
    path('amakenotice/', views.amakenotice, name='amakenotice'),
    path('notices', views.notices, name='notices'),
    path('notices/n/<int:no_id>/', views.shownotice, name='shownotice'),
    path('notices/<int:n_id>/', views.delnotice, name='delnotice'),
    path('notices/editnotice/<int:edit_id>', views.editnotice, name='editnotice'),

    path('residents/bills/<int:p_id>/', views.showbill, name ='showbill'),
    path('residents/bills/view/<int:bill_id>/<int:p_id>/', views.billview, name ='billview'),
    path('residents/bills/del/<int:bill_id>/', views.billdelete, name ='billdelete'),
    path('residents/bills/create/<int:pr_id>/', views.createbill, name ='createbill'),
    path('residents/massbill', views.massbill, name='massbill'),
    path('allbills', views.allbills, name='allbills'),
    path('paidbills', views.paidbills, name='paidbills'),
    path('latebills', views.latebills, name='latebills'),
    path('duebills', views.duebills, name='duebills'),

    path('complaints/c/<int:co_id>/', views.deletecomplaint, name='deletecomplaint'),
    path('complaints/<int:c_id>/',views.opencomplaint, name='opencomplaint'),
    path('complaints', views.complaints, name='complaints'),
    path('complaints/resolve/<int:c_id>/', views.resolve, name='resolve')
     
]

sec/models.py
from django.db import models

# Create your models here.

main/forms.py
from email.policy import default
from django import forms
from django.forms import ModelForm
from .models import Complaint, Notice, Service, Visitor, Bills
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime
from django.core.mail import EmailMessage
from django.core.mail import send_mail
from django.conf import settings 
class NewUserForm(UserCreationForm):
    c = (
        ("r", "Resident"),
        ("s", "Staff"),
        ("a", "Superuser")
    )
    email = forms.EmailField(required=True)
    age = forms.IntegerField()
    photo = forms.ImageField()
    flat_no = forms.CharField(max_length=10, required=True)
    phone_number = forms.IntegerField()
    name=forms.CharField(max_length=100)
    status = forms.ChoiceField(choices=c)
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", 'name','age', 'flat_no'
                , 'phone_number','photo')
        def save(self, commit=True):
            user =  super(NewUserForm, self).save(commit=False)
            user.name = self.cleaned_data['name']
            user.email = self.cleaned_data['email']
            user.age = self.cleaned_data['age']
            user.flat_no = self.cleaned_data['flat_no']
            user.phone_number = self.cleaned_data['phone_number']
            user.status = self.cleaned_data['status']
            user.photo = self.cleaned_data['photo']

            if commit:
                user.save()
            return user

class otpForm(ModelForm):
    class Meta:
        model = Visitor
        fields = ['otp']
    otp = forms.CharField(required=True)
    def __init__(self, *args, **kwargs):
        super(otpForm, self).__init__(*args, **kwargs)
        self.fields['otp'].label = "Enter the OTP:"

class ComplaintForm(ModelForm):
    class Meta:
        model = Complaint
        fields = ['subject', 'content']


    subject = forms.CharField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )


class NoticeForm(ModelForm):
    class Meta:
        model = Notice
        fields = ['header_notice', 'details_notice']

    header_notice = forms.CharField(required=True)
    details_notice = forms.CharField(required=True,widget=forms.Textarea)


    def __init__(self, *args, **kwargs):
        super(NoticeForm, self).__init__(*args, **kwargs)
        self.fields['header_notice'].label = "Specify the subject:"
        self.fields['details_notice'].label = "Enter the content of the notice:"


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ['service_name','service_details']

    demo_choice = (
                    ("1", "Electrician"),
                    ("2", "Internet Service Provider"),
                    ("3", "Plumber"),
                  )
    service_name = forms.ChoiceField(choices = demo_choice )
   
    service_details = forms.CharField(required=True,widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super(ServiceForm, self).__init__(*args, **kwargs)
 
        self.fields['service_details'].label = "Specify your request:"


class VisitorForm(ModelForm):
    class Meta:
        model = Visitor
        fields = ['visitor_name', 'visitor_phone', 'visiting_flat', 'visiting_date', 'visiting_time']


    visitor_name = forms.CharField(max_length=100, required = True)
    visitor_phone =  forms.IntegerField(required = True)
    visiting_flat = forms.CharField(max_length=100, required = True)
    visiting_date = forms.DateField(required = True)
    visiting_time = forms.TimeField(required = True)

class BillForm(ModelForm):
    class Meta:
        model = Bills
        fields = ['repairs_maintenance_charges', 'society_service_charges', 'sinking_fund_charges',
                 'parking_charges', 'charity_charges', 'due_date']
    
    repairs_maintenance_charges = forms.IntegerField()
    society_service_charges = forms.IntegerField()
    sinking_fund_charges = forms.IntegerField()
    parking_charges = forms.IntegerField()
    charity_charges = forms.IntegerField()
    due_date = forms.DateTimeField()

sec/forms.py
from email.policy import default
from pyexpat import model
from django import forms
from django.forms import ModelForm
from main.models import Complaint, Notice, Service, Visitor, Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import datetime

class EditForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name','email', 'age', 'flat_no', 'phone_number', 'status','photo']
    
    ch = (
        ("r", "Resident"),
        ("s", "Staff"),
        ("a", "Superuser")
    )
    name = forms.CharField()
    age = forms.IntegerField()
    email = forms.EmailField()
    flat_no = forms.CharField()
    photo = forms.ImageField(required=False)
    phone_number = forms.IntegerField()
    status = forms.ChoiceField(choices=ch, required=False)

class EditNoticeForm(ModelForm):
    class Meta:
        model = Notice
        fields = ['header_notice','details_notice', 'showflag']
    header_notice = forms.CharField(required=True)
    details_notice = forms.CharField(
        required=False,
        widget=forms.Textarea)
    ch = (("y", "Show"), ("n", "Hide"))    
    showflag = forms.ChoiceField(choices=ch)

class ResolveForm(ModelForm):
    class Meta:
        model = Complaint
        fields = ['resolve_msg']
    resolve_msg = forms.CharField(
        required=True,
        widget=forms.Textarea)

sec/templates/sec/addvisitor.html
{% extends "sec/header.html" %} {% block content %}
<h3 style="text-align: center;">Register New Visitor</h3>
<form action="" method="post">
    {% csrf_token %} 
<p><label style="font-weight: bolder;" for="id_visitor_name">Visitor name:</label> <input class="form-control" type="text" name="visitor_name" maxlength="100" required="" id="id_visitor_name"></p>
<p><label style="font-weight: bolder;" for="id_visitor_phone">Visitor phone:</label> <input class="form-control" type="number" name="visitor_phone" required="" id="id_visitor_phone"></p>
<p><label style="font-weight: bolder;" for="id_visiting_flat">Visiting flat:</label> <input class="form-control" type="text" name="visiting_flat" maxlength="100" required="" id="id_visiting_flat"></p>
<p><label style="font-weight: bolder;" for="id_visiting_date">Visiting date:  </label> <input class="datepicker" type="date" name="visiting_date" required="" id="id_visiting_date"></p>
<p><label style="font-weight: bolder;" for="id_visiting_time">Visiting time:  </label> <input class="timepicker" type="time" name="visiting_time" required="" id="id_visiting_time"></p><br>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Submit</button><br>
</form>
{% endblock %}

sec/templates/sec/billcreate.html
{% extends "sec/header.html" %} {% block content %}
<h1 style="text-align:center;">Create a Bill</h1>

<form action="" method="post">
    {% csrf_token %}
    <!-- {{form.as_p}} -->
    <p><label style="font-weight: bolder;" for="id_repairs_maintenance_charges">Repairs maintenance charges:</label> <input class="form-control" type="number" name="repairs_maintenance_charges" value="500" required="" id="id_repairs_maintenance_charges"></p>
  <p><label style="font-weight: bolder;" for="id_society_service_charges">Society service charges:</label> <input class="form-control" type="number" name="society_service_charges" required="" id="id_society_service_charges"></p>
  <p><label style="font-weight: bolder;" for="id_sinking_fund_charges">Sinking fund charges:</label> <input class="form-control" type="number" name="sinking_fund_charges" required="" id="id_sinking_fund_charges"></p>
  <p><label style="font-weight: bolder;" for="id_parking_charges">Parking charges:</label> <input class="form-control" type="number" name="parking_charges" required="" id="id_parking_charges"></p>
  <p><label style="font-weight: bolder;" for="id_charity_charges">Charity charges:</label> <input class="form-control" type="number" name="charity_charges" required="" id="id_charity_charges"></p>
  <p><label style="font-weight: bolder;" for="id_due_date">Due date:  </label> <input class="browser-default" type="datetime-local" name="due_date" required="" id="id_due_date"></p> <br>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Post</button>
</form>

{% endblock %}

sec/templates/sec/billview.html
{% extends "sec/header.html" %} {% block content %}

<head>

    <meta charset="utf-8">

    <!-- Load paper.css for happy printing -->


    <!-- Set page size here: A5, A4 or A3 -->
    <!-- Set also "landscape" if you need -->
    <style>@page {
        size: A4 portrait;
        margin-top: 8px;
        margin-bottom: 10px;
        margin-left: 20px;
    }</style>
    <style>
        /* Three image containers (use 25% for four, and 50% for two, etc) */
        .column {
            float: left;
            padding: 5px;
        }

        /* Clear floats after image containers */
        .row::after {
            content: "";
            clear: both;
            display: table;
        }

        table tbody tr td {
            padding: 2px !important;
            line-height: 1.35 !important;
        }

        @media print {
            .box-body {
                margin-top: 10px !important;
                margin-bottom: 10px;
            }
        }
    </style>

    <script type="text/javascript">
      function printPageArea(areaID){
        var printContent = document.getElementById(areaID);
        var WinPrint = window.open('', '', 'width=900,height=650');
        WinPrint.document.write(printContent.innerHTML);
        WinPrint.document.close();
        WinPrint.focus();
        WinPrint.print();
        WinPrint.close();
    }
    </script>
    <style>
        .center-me {
            font-size: 15px;
            margin: auto;
            height: 10px;
            max-width: 500px;
            margin: 75px auto 40px auto;
            display: flex;
        }
    </style>
</head>

<body class="A4 portrait">


<section class="sheet" id="content-print">
    <style>
        table {
            /* border-collapse: unset !important; */
        }
    </style>
<div id="printableArea">
    <div class="box-body" id="box_data" style="display: flex;padding: 5px 10px 0 10px;margin-bottom: -21px;">
        <div style="width: 100%;padding-right: 10px;" class="col-md-12">
            <div class="row">
                <div class="col-lg-4" style="width: 70%;padding-left: 20px;">
                    <h4 style="text-align:center;">MAINTENANCE BILL</h4>
                </div>

            </div>

            <br>




            <table width="100%" border="1">
                <tr style="background: rgba(217,225,242,1.0)">
                    <th class="text-center" colspan="2" style="width: 25%;">Bill To</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Name</th>
                    <th>{{profile.name}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Flat Number</th>
                    <th>{{profile.flat_no}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Email</th>
                    <th>{{profile.email}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Bill ID</th>
                    <th>{{bill.bill_id}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Published</th>
                    <th>{{bill.publish_date}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Due</th>
                    <th>{{bill.due_date}}</th>
                </tr>
                {% if bill.status == 'y' %}
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Payment Time</th>
                    <th>{{bill.payment_time}}</th>
                </tr>
                {% endif %}
            </table>
            <br>
            <table width="100%" border="1px">
                <tr style="background: rgba(217,225,242,1.0);">
                    <th class="text-center">
                        Sr No.
                    </th>
                    <th class="text-center" colspan="3">
                        Particulars
                    </th>
                    <th class="text-center">
                        Amount
                    </th>
                </tr>
                <tbody>

                <tr><td>1</td><td colspan="3">Repairs and Maintenance Fund</td><td>{{bill.repairs_maintenance_charges}}</td></tr>
                <tr><td>2</td><td colspan="3">Society Service Charges</td><td>{{bill.society_service_charges}}</td></tr>
                <tr><td>3</td><td colspan="3">Parking Charges</td><td>{{bill.parking_charges}}</td></tr>
                <tr><td>4</td><td colspan="3">Sinking Fund</td><td>{{bill.sinking_fund_charges}}</td></tr>
                <tr><td>5</td><td colspan="3">Charity Fund</td><td>{{bill.charity_charges}}</td></tr>
                </tbody>



                <tfoot>
                <tr style="background: rgba(217,225,242,1.0);">
                    <td colspan="4">Total Amount</td>
                    <td colspan="1">{{total}}</td>
                </tr>
                
                
                </tfoot>


            </table>
            <br>

        </div>

    </div>
</div><br>
<a href="/admin/residents/bills/{{profile.id}}" class="btn">Back</a>
<a href="javascript:void(0);" class="btn" onclick="printPageArea('printableArea')">Print</a><br><br>
</section>
</body>
<style media="screen">
  a.btn{
    position:relative;
    left:500px;
  }
  h4{
    position:relative;
    left:150px;
  }
</style>
{% endblock %}

sec/templates/sec/duebills.html
{% extends "sec/header.html" %} {% block content %}
<h5 style="text-align: center;">Due Bills</h5>
<table class="table">
    <tr class="hmm" style="font-weight: bolder;">
      <td>Name</td>
      <td>Flat Number</td>
      <td>Bill ID</td>
      <td>Publish Date</td>
      <td>Due Date</td>
      <td></td>
      <!-- <td> </td> -->
    </tr>
    {% for b in due %}
    
    <tr>
      <td>{% for p in profile %}
        {% if p.user == b.user %}
      {{p.name}}
    {% endif %}
  {% endfor %}</td>
      <td>{{b.flat_no_and_date}}</td> 
      <td>{{b.bill_id}}</td>
      <td>{{b.publish_date}}</td>
      <td>{{b.due_date}}</td>
      {% for p in profile %}
        {% if p.user == b.user %}
        <td><a href="residents/bills/view/{{b.id}}/{{p.id}}">View</a></td>
    {% endif %}
  {% endfor %}
    </tr>

    {% endfor %}

  </table>
  {% endblock %}

sec/templates/sec/editnotice.html
{% extends "sec/header.html" %} {% block content %}
<h3 style="text-align:center;">Edit Notice</h3>
<form role="form" action="" method="post">
    <!-- {{form.as_p}} -->
    {% csrf_token %}
<p><label style="font-weight: bolder;" for="id_header_notice">Subject:</label> <input class="form-control" type="text" value="{{notice.header_notice}}" name="header_notice" required="" id="id_header_notice"></p>
<p><label style="font-weight: bolder;" for="id_details_notice">Details notice:</label> <textarea class="form-control" name="details_notice" cols="40" rows="10" required="" id="id_details_notice">{{notice.details_notice}}</textarea></p>
<p><label style="font-weight: bolder;" for="id_showflag">Status:</label> <select class="form-control" name="showflag" id="id_showflag">
  <option value="y">Show</option>

  <option value="n">Hide</option>

</select></p>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Save Changes</button><br>
</form>

{% endblock %}

sec/templates/sec/login.html
<html><head>
    
    <link rel="stylesheet" href="/static/tiny/css/prism">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="/static/main/css/materialize.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
          $('select').formSelect();
      })
    </script>

</head>

<body>
    
<nav>
    <div class="nav-wrapper #1976d2 blue darken-2">
        <a href="" class="brand-logo">E-Housing Society</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            
            
              <li><a href="/login"></a></li>
            
        </ul>
    </div>
</nav>

<style media="screen">
  a.brand-logo{
    margin-left: 15px;
  }
</style>

    

    
    <br><br>
    <div class="container">
<h1 style="text-align: center;">ADMIN LOGIN</h1>
<form action="" method="post">
    {% csrf_token %} <p><label for="id_username" class="active">Username:</label> <input type="text" name="username" autofocus="" autocapitalize="none" autocomplete="username" maxlength="150" required="" id="id_username"></p>
<p><label for="id_password" class="active">Password:</label> <input type="password" name="password" autocomplete="current-password" required="" id="id_password"></p> <br>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Login</button>
</form>

 </div>


<script src="/static/tinymce/js/prism.js"></script>
</body></html>

sec/templates/sec/makenotice.html
{% extends "sec/header.html" %} {% block content %}
<h1 style="text-align:center;">Post a Notice</h1>


    <form role="form" action="" method="post" class="form-group">
        {% csrf_token %}
        <!-- {{form.as_p}} -->
        <p><label for="id_header_notice" style="font-weight: bolder;">Specify the subject:</label> <input class="form-control" type="text" name="header_notice" required="" id="id_header_notice"></p>
    <p><label for="id_details_notice" style="font-weight: bolder;">Enter the content of the notice:</label> <textarea class="form-control" name="details_notice" cols="40" rows="10" required="" id="id_details_notice"></textarea></p>
   
        <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Post</button>
    </form>

    

{% endblock %}

sec/templates/sec/massbill.html
{% extends "sec/header.html" %} {% block content %}
<h3 style="text-align: center;">Mass Billing</h3>

  <form action="" method="post">
  {% csrf_token %} 
  <p><label style="font-weight: bolder;" for="id_repairs_maintenance_charges">Repairs maintenance charges:</label> <input class="form-control" type="number" name="repairs_maintenance_charges" required="" id="id_repairs_maintenance_charges"></p>
  <p><label style="font-weight: bolder;" for="id_society_service_charges">Society service charges:</label> <input class="form-control" type="number" name="society_service_charges" required="" id="id_society_service_charges"></p>
  <p><label style="font-weight: bolder;" for="id_sinking_fund_charges">Sinking fund charges:</label> <input class="form-control" type="number" name="sinking_fund_charges" required="" id="id_sinking_fund_charges"></p>
  <p><label style="font-weight: bolder;" for="id_parking_charges">Parking charges:</label> <input class="form-control" type="number" name="parking_charges" required="" id="id_parking_charges"></p>
  <p><label style="font-weight: bolder;" for="id_charity_charges">Charity charges:</label> <input class="form-control" type="number" name="charity_charges" required="" id="id_charity_charges"></p>
  <p><label style="font-weight: bolder;" for="id_due_date">Due date:</label> <input class="form-control" type="datetime-local" name="due_date" required="" id="id_due_date"></p>
 
  
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Submit</button><br>
</form>
{% endblock %}

sec/templates/sec/notices.html
{% extends "sec/header.html" %} {% block content %}
<div class="container">
  <br>
<h4 style="text-align:center;">Notices Posted on the Noticeboard</h4>
<br>
  <table class="table">
    <tr>
      <td style="font-weight: bold;">Subject</td>
      <td style="font-weight: bold;">Publish Date and Time</td>
      <td style="font-weight: bold;">Status</td>
      <td></td>
      <!-- <td></td> -->
    </tr>
    {% for v in notice reversed %}
    <tr>
      <td>{{v.header_notice}}</td>
      <td>{{v.publish_dt}}</td>
      <td>{% if v.showflag == 'y' %} Shown {% else %} Hidden {% endif %}</td>
      <td><a href="/admin/notices/n/{{v.id}}/">View</a></td>
      <!-- <td><a href="{% url 'sec:delnotice' v.id %}">Delete</a></td> -->
    </tr>
    {% endfor %} 
  </table><br><br>
  <!-- <div style="text-align: center;">
    <a class="btn" style='background-color: blanchedalmond; color: brown;' href="{% url 'sec:amakenotice' %}">ADD NOTICE</a>
  </div> -->

{% endblock %}

sec/templates/sec/paidbills.html
{% extends "sec/header.html" %} {% block content %}
<h5 style="text-align: center;">Paid Bills</h5>
<table class="table">
    <tr class="hmm" style="font-weight: bolder;">
      <td>Name</td>
      <td>Flat Number</td>
      <td>Bill ID</td>
      <td>Due Date</td>
      <td>Payment Time</td>
      <td></td>
      <td> </td>
    </tr>
    {% for b in paid %}
    
    <tr>
      
      <td>{% for p in profile %}
        {% if p.user == b.user %}
      {{p.name}}
    {% endif %}
  {% endfor %}</td>
      <td>{{b.flat_no_and_date}}</td> 
      <td>{{b.bill_id}}</td>
      <td>{{b.due_date}}</td>
      <td>{{b.payment_time}}</td>
      {% for p in profile %}
        {% if p.user == b.user %}
        <td><a href="residents/bills/view/{{b.id}}/{{p.id}}">View</a></td>
    {% endif %}
  {% endfor %}
    </tr>
    {% endfor %}


{% endblock %}

sec/templates/sec/pendingbills.html
{% extends "sec/header.html" %} {% block content %}
<h5 style="text-align: center;">Pending Bills</h5>
  <table class="table">
      <tr class="hmm" style="font-weight: bolder;">
        <td>Name</td>
        <td>Flat Number</td>
        <td>Bill ID</td>
        <td>Publish Date</td>
        <td>Due Date</td>
        <td></td>
        <!-- <td> </td> -->
      </tr>
      {% for b in pending %}
      
      <tr>
        <td>{% for p in profile %}
          {% if p.user == b.user %}
        {{p.name}}
      {% endif %}
    {% endfor %}</td>
        <td>{{b.flat_no_and_date}}</td> 
        <td>{{b.bill_id}}</td>
        <td>{{b.publish_date}}</td>
        <td>{{b.due_date}}</td>
        {% for p in profile %}
        {% if p.user == b.user %}
        <td><a href="residents/bills/view/{{b.id}}/{{p.id}}">View</a></td>
    {% endif %}
  {% endfor %}
      </tr>
  
      {% endfor %}
  
    </table>

    {% endblock %}

sec/templates/sec/resolve.html
{% extends "sec/header.html" %} {% block content %}
<h4 style="text-align:center;">Resolve Complaint</h4>
<form action="" method="post">
    {% csrf_token %}
    <p><label style="font-weight: bolder;" for="id_resolve_msg">Resolve msg:</label> <textarea class="form-control" name="resolve_msg" cols="40" rows="10" required="" id="id_resolve_msg"></textarea></p>
    <button type="submit" class="btn" style="background-color: blanchedalmond; color: brown;">Submit</button>
</form>

{% endblock %}

sec/templates/sec/showcomplaints.html
{% extends "sec/header.html" %} {% block content %}
<br>
<h4 style="text-align:center;">Resident's Complaints</h4>
<br>
<div class="container">
  <table class="table">
    <tr style="font-weight: bolder;">
      <td>Name</td>
      <td>Flat Number</td>
      <td>Subject</td>
      <td>Published On</td>
      <td>Status</td>
      <td></td>
    </tr>
    {% for v in comp %}
    <tr>
      <td>{{v.name}}</td>
      <td>{{v.flat_no}}</td>
      <td>{{v.subject}}</td>
      <td>{{v.date}}</td>
      <td>{% if v.status == 'y' %}Resolved{% else %}Not Resolved{% endif %}</td>
      <td><a href="/admin/complaints/{{v.id}}">View</a></td>
    </tr>
    {% endfor %} 
  </table><br><br>
{% endblock %}

sec/templates/sec/shownotice.html
{% extends "sec/header.html" %} {% block content %}
{% csrf_token %}
<br><br>
<div class="card">
    <div class="card-body">
       <h5>Notice Heading: {{notice.header_notice}}</h5> 
    </div>
  </div><br>
  <div class="card">
    <div class="card-body">
        <h5>Content:</h5> <br> {{notice.details_notice}}
    </div>
  </div><br>
  <div class="card">
    <div class="card-body">
        <h6>Status:</h6>{% if notice.showflag == 'y' %} Shown {% else %} Hidden {% endif %}
    </div>
  </div><br>
  <div>
    <a class="btn" style='background-color: blanchedalmond; color: brown;' href="{% url 'sec:notices' %}">Back</a> <br>
  </div>
  <br>
  <div>
    <a class="btn" style='background-color: rgb(59, 105, 255); color: rgb(255, 255, 255);' href="/admin/notices/editnotice/{{notice.id}}">Edit Notice</a> <br><br>
  </div>

{% endblock %}