final_society/urls.py
from django.contrib import admin
from django.urls import path, include
admin.site.site_header = 'E-House Care Admin Interface'
admin.site.site_title = 'E-House Care'
admin.site.intex_title = 'Database Management System'
urlpatterns = [
    path('admin1/', admin.site.urls),
    path('', include('main.urls')),
    path('admin/', include('sec.urls')),
]

main/urls.py
from django.urls import path, include
from .import views
from django.conf.urls.static import static
from django.conf import settings
app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_request, name='logout'),
    path('login/', views.login_request, name='login'),
    path('noticeboard', views.noticeboard, name='noticeboard'),
    path('complaint/', views.complaint, name='complaint'),
    path('staff/', views.staff, name='staff'),
    path('makenotice', views.makenotice, name='makenotice'),
    path('service', views.service, name='service'),
    path('searchbill', views.searchbill, name='searchbill'),
    path('<int:bill_id>/', views.viewbill, name='viewbill'),
    path('addvisitor', views.addvisitor, name='addvisitor'),
    path('otpfunc', views.otpfunc, name='otpfunc'),
    path('visitor', views.visitor, name='visitor'),
    path('bill/<int:bill_id>', views.viewbill, name='viewbill'),
    path('pay/<int:bill_id>', views.pay, name='pay'),
    path('test', views.test, name='test'),
    path('psuccess/<int:bill_id>' , views.success , name='success'),
    path('notif', views.notif, name='notif'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sec/urls.py
from pydoc import resolve
from django.conf import settings
from django.urls import path
from main.views import *
from .import views 
app_name='sec'

urlpatterns = [

    path('hello', views.hello, name='hello'),

    path('', views.adminlogin, name='adminlogin'),
    path('ahome', views.ahome, name = 'ahome'),

    path('visitor', views.visitor, name='visitor'),
    path('addvisitor', views.addvisitor, name='addvisitor'),
    path('visitor/<int:v_id>/', views.delvisitor, name='delvisitor'),
    path('otpfunc/<int:vi_id>/', views.otpfunc, name='otpfunc'),

    path('residents', views.residents, name='residents'),
    path('register', views.register, name='register'),
    path('<int:del_id>/', views.deleteuser, name='deleteuser'),
    path('residents/<int:profile_id>/', views.showprof, name='showprof'),
    
    path('amakenotice/', views.amakenotice, name='amakenotice'),
    path('notices', views.notices, name='notices'),
    path('notices/n/<int:no_id>/', views.shownotice, name='shownotice'),
    path('notices/<int:n_id>/', views.delnotice, name='delnotice'),
    path('notices/editnotice/<int:edit_id>', views.editnotice, name='editnotice'),

    path('residents/bills/<int:p_id>/', views.showbill, name ='showbill'),
    path('residents/bills/view/<int:bill_id>/<int:p_id>/', views.billview, name ='billview'),
    path('residents/bills/del/<int:bill_id>/', views.billdelete, name ='billdelete'),
    path('residents/bills/create/<int:pr_id>/', views.createbill, name ='createbill'),
    path('residents/massbill', views.massbill, name='massbill'),
    path('allbills', views.allbills, name='allbills'),
    path('paidbills', views.paidbills, name='paidbills'),
    path('latebills', views.latebills, name='latebills'),
    path('duebills', views.duebills, name='duebills'),

    path('complaints/c/<int:co_id>/', views.deletecomplaint, name='deletecomplaint'),
    path('complaints/<int:c_id>/',views.opencomplaint, name='opencomplaint'),
    path('complaints', views.complaints, name='complaints'),
    path('complaints/resolve/<int:c_id>/', views.resolve, name='resolve')
     
]

main/models.py
from pydoc import resolve
from tokenize import blank_re
from django.db import models
from django.db.models.fields import CharField, TextField, EmailField, IntegerField
from django.contrib.auth.models import User
from django.contrib.auth.models import UserManager
from datetime import date, datetime
import datetime
class MainPage(models.Model):
    society_name = CharField(max_length=200)
    society_about = TextField()

    def __str__(self):
        return self.society_name

class Profile(models.Model):
    ch = (
        ("r", "Resident"),
        ("s", "Staff"),
        ("a", "Superuser")
    )
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True)
    email = models.EmailField()
    age = models.IntegerField(blank=True)
    flat_no = models.CharField(max_length=10)
    phone_number = models.IntegerField()
    photo = models.ImageField(null=True,upload_to='main/images', blank =True)
    status = models.CharField(max_length = 1, null=True, choices=ch)
    def __str__(self):
        return str(self.flat_no+' '+self.name)


class Notice(models.Model):
    ch = (
        ("y", "Show"),
        ("n", "Hide")
    )
    header_notice = CharField(max_length=100)
    details_notice = TextField()
    showtill = models.DateTimeField(blank=True, default=(datetime.datetime.now() + datetime.timedelta(days=1)))
    showflag = models.CharField(max_length=1, blank=True, choices=ch)
    publish_dt = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def __str__(self):
        return self.header_notice

class Complaint(models.Model):
    username = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    flat_no = models.CharField(max_length=100, null=True)
    date = models.DateTimeField(null=True)
    subject = models.CharField(null=True, max_length=100)
    content = models.TextField(null=True)
    ch =(("y", "Resolved"), ("n", "Not Resolved"))
    status = models.CharField(max_length=1,null=True, choices=ch)
    resolve_msg = models.TextField(null=True)
    resolve_time = models.DateTimeField(null=True)
    complaint_user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.complaint_user)

class Staff(models.Model):
    staff_name = models.CharField(max_length=100)
    staff_email = models.EmailField()
    staff_phone = models.IntegerField()
    designation = models.CharField(max_length=100)
    about = models.TextField(null=True)
    image = models.ImageField(upload_to='main/images')
    def __str__(self):
        return str(self.designation)

class Visitor(models.Model):
    visitor_name = models.CharField(max_length=100)
    visitor_phone =  models.IntegerField()
    visiting_flat = models.CharField(max_length=100)
    visiting_date = models.DateField(default=datetime.date.today)
    visiting_time = models.TimeField(default=datetime.datetime.now)
    def __str__(self):
        return str(self.visitor_name)



class Service(models.Model):
    service_name=models.CharField(max_length=100)
    service_email=models.EmailField(null=True)
    service_details=models.TextField(blank=True)
    def __str__(self):
        return str(self.service_name)


class Bills(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    ch = (("y", "Paid"), ("n", "Pending"))
    status = models.CharField(max_length=1, choices=ch, blank=True)
    payment_time = models.DateTimeField(blank=True, default=datetime.datetime.now)
    bill_id = models.CharField(max_length=100, null=True)
    repairs_maintenance_charges = models.IntegerField()
    society_service_charges = models.IntegerField()
    sinking_fund_charges = models.IntegerField(default=80)
    parking_charges = models.IntegerField(default=100)
    charity_charges = models.IntegerField(default=20)
    previous_dues = models.IntegerField(default=0, null=True)
    publish_date = models.DateTimeField(default=datetime.datetime.now, blank=True)
    due_date = models.DateTimeField(blank=True)
    flat_no_and_date = models.CharField(max_length=100)

    def __str__(self):
        return str(self.flat_no_and_date)

main/views.py
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from requests import get
from main.forms import NewUserForm, ComplaintForm, NoticeForm, ServiceForm, VisitorForm, otpForm
from main.models import MainPage
from .models import Complaint, MainPage, Notice, Staff, Profile, Service, Bills, Visitor
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMessage
from django.db.models import Sum
from django.db.models import F
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
import os
from twilio.rest import Client
import random
import http.client
import pytz
import razorpay
from django.views.decorators.csrf import csrf_exempt


def homepage(request):
    if request.user.is_authenticated:
        # for u in User.objects.all():
        #     if u.username=='Sachin':
        #         prof = Profile.objects.get(user = u)
        #         u.is_staff
        #         u.save()
        #         prof.status='s'
        #         prof.save()
        #for displaying latest notice on noticeboard:
        max = Notice.objects.get(id = 1)
        utc=pytz.UTC
        maxtime = max.publish_dt.replace(tzinfo=utc)
        for notice in Notice.objects.all():
            noticetime = notice.publish_dt.replace(tzinfo = utc)
            maxtime = max.publish_dt.replace(tzinfo=utc)
            if notice.showflag == 'y':
                if noticetime > maxtime:
                    newestnotice = notice
                    max = notice
                else:
                    newestnotice = max 
        
        #for displaying latest notification
        max = Complaint.objects.filter(complaint_user = request.user)
        newestc=[]
        if max:
            maxi = max[0]
            user = request.user
            utc=pytz.UTC
            newestc = []
            if maxi.status == 'y':
                maxitime = maxi.resolve_time.replace(tzinfo=utc)
                if user.is_authenticated:
                    for c in Complaint.objects.filter(complaint_user = request.user):
                        if c.status == 'y':
                            ctime = c.resolve_time.replace(tzinfo = utc)
                            maxitime = maxi.resolve_time.replace(tzinfo=utc)
                            if ctime > maxitime:
                                newestc = c
                                maxi = c   
                            else:
                                newestc = maxi
        #for displaying the latest bill for that user
        if request.user.username == 'admin':
        
            newestc = []
            billsend=[]
        else:

            max = Bills.objects.filter(user = request.user)
            billsend=[]
            if max:
                for b in max:
                    x = b.bill_id
                maxi = Bills.objects.get(bill_id = x)
                user = request.user
                utc=pytz.UTC
                maxitime = maxi.publish_date.replace(tzinfo=utc)
                if user.is_authenticated:
                    for bill in Bills.objects.filter(user = request.user):
                        if bill.status == 'n':
                            billtime = bill.publish_date.replace(tzinfo=utc)
                            maxitime = maxi.publish_date.replace(tzinfo=utc)
                            if billtime>maxitime:
                                billsend = billtime
                                maxi = billtime
                            else:
                                billsend = maxi    
        
        return render(request=request,
                    template_name='main/home.html',
                    context={'notice':newestnotice, 'complaint':newestc, 'bill':billsend, 'iprofile':Profile.objects.all()})
    else:
        return redirect('main:login')


def register(request):

    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'New Account Created!: {username}')
            login(request, user)
            messages.info(request, f'You are now logged in as: {username}')
            return redirect("main:homepage")
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg}: {form.error_messages[msg]}")

    form = NewUserForm
    return render(request, "main/register.html", context={'form': form, 'iprofile':Profile.objects.all()})


def logout_request(request):
    logout(request)
    messages.info(request, 'Logged out successfully!')
    return render(request,"main/home.html")


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'You are now logged in')
                return redirect('main:homepage')
            else:
                messages.error(request, f'Invalid username or password')
        else:
            messages.error(request, f'Invalid username or password')

    form = AuthenticationForm()
    return render(request, "main/login.html", {'form': form})


def noticeboard(request):
    
    utc=pytz.UTC
    noticelist = []
    current = datetime.datetime.now()
    currenttime = current.replace(tzinfo=utc)
    for notice in Notice.objects.all():
        noticetime = notice.showtill.replace(tzinfo=utc)
        if notice.showflag == 'y':
            if noticetime >= currenttime:
                noticelist.append(notice)
            else:
                if notice.showflag == 'y':
                    noticelist.append(notice)
                else:
                    notice.showflag = 'n'
    
    messages.info(request, 'You are viewing the Notice Board!')
    return render(request, "main/noticeboard.html", {'noticeboard': noticelist, 'iprofile':Profile.objects.all()})

def notif(request):
    complaintlist=[]
    user = request.user
    for c in Complaint.objects.filter(complaint_user = user):
        print(c)
        if c.status == 'y':
            complaintlist.append(c)
    return render(request, 'main/notif.html', {'complaint': complaintlist, 'iprofile':Profile.objects.all()})

def complaint(request):
    if request.method == 'POST':         
        form = ComplaintForm(request.POST)
        if form.is_valid():
            
            comp = User.objects.get(username = request.user.username)
            # u = User.objects.all()
            
            u1 = request.user.username
            n1 = Profile.objects.get(user = request.user)
            
            newdate = datetime.datetime.now()
            h1 = form.cleaned_data.get('subject')
            h2 = form.cleaned_data.get('content')
            status = 'n'

            newcomp = Complaint(subject = h1, content = h2,flat_no =n1.flat_no, complaint_user = comp, date = newdate, username = u1, name=n1.name, status = status )
            newcomp.save()
            messages.info(request, 'Complaint registered successfully!')
            return redirect('main:homepage')

    return render(request, "main/complaint.html", context={'form': ComplaintForm(), 'iprofile':Profile.objects.all()})    


def staff(request):
    staff = Staff.objects.all()
    return render(request, "main/staff.html", context={'staff': staff, 'iprofile':Profile.objects.all()})


def makenotice(request):
    note = Notice()
    if request.method == 'GET':
        return render(request, "main/makenotice.html", context={'form': NoticeForm()})
    else:
        form = NoticeForm(request.POST)
        newnotice = form.save(commit=False)
        newnotice.user = request.user

        subject = newnotice.header_notice
        message = newnotice.details_notice
        from_email = settings.EMAIL_HOST_USER
        recievers = []
        for user1 in Profile.objects.all():
            recievers.append(user1.email)
        emailsending = EmailMessage(subject, message, from_email, recievers)
        emailsending.send()

        newnotice.save()
        messages.info(request, 'Notice made successfully!')
        return redirect('main:homepage')

def service(request):
    if request.method == 'GET':
        return render(request, "main/service.html", context={'form': ServiceForm(), 'iprofile':Profile.objects.all()})
    else:
        form = ServiceForm(request.POST)
        if form.is_valid():
            profile = Profile.objects.get(user = request.user)
            msg = form.cleaned_data.get('service_details')
            sname = form.cleaned_data.get('service_name')
            if sname == '1':
                subject = 'Request from '+ profile.name + ' --- flat number: '+ profile.flat_no
                message = msg
                from_email = settings.EMAIL_HOST_USER
                recievers = ['mihirbhatkar87@gmail.com']
                emailsending = EmailMessage(subject, message, from_email, recievers)
                emailsending.send()
            elif sname == '2':
                subject = 'Request from '+ profile.name + ' --- flat number: '+ profile.flat_no
                message = msg
                from_email = settings.EMAIL_HOST_USER
                recievers = ['21rihim@gmail.com']
                emailsending = EmailMessage(subject, message, from_email, recievers)
                emailsending.send()
            elif sname == '3':

main/templates/main/addvisitor.html
<html>
	<head>
		<link rel="stylesheet" href="/static/tiny/css/prism" />
		<!-- Compiled and minified CSS -->
		<link rel="stylesheet" href="/static/main/css/materialize.css" />
		<!-- Compiled and minified JavaScript -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function () {
				$("select").formSelect();
				$(".datepicker").datepicker();
			});
		</script>
	</head>

	<body>
		<nav>
			<div class="nav-wrapper #1976d2 blue darken-2">
				<a href="/" class="brand-logo">grooveCare</a>
				<ul id="nav-mobile" class="right hide-on-med-and-down">
					<li><a href="/">Home</a></li>

					<li><a href="/makenotice">Make Notice</a></li>
					<li><a href="/addvisitor">Add Visitors</a></li>
					<li><a href="/visitor">Visitors Log</a></li>

					<li><a href="/noticeboard">Notice Board</a></li>

					<li><a href="/logout">Logout</a></li>
				</ul>
			</div>
		</nav>
		<style media="screen">
			a.brand-logo {
				margin-left: 15px;
			}
		</style>

		<br /><br />
		<div class="container">
			<h1 style="text-align: center">Add Visitors</h1>
			<form role="form" action="" method="post">
				{% csrf_token %}
				<p>
					<label for="id_visitor_name">Visitor name:</label>
					<input
						type="text"
						name="visitor_name"
						maxlength="100"
						required=""
						id="id_visitor_name"
					/>
				</p>
				<p>
					<label for="id_visitor_phone">Visitor phone:</label>
					<input
						type="number"
						name="visitor_phone"
						required=""
						id="id_visitor_phone"
					/>
				</p>
				<p>
					<label for="id_visiting_flat">Visiting flat:</label>
					<input
						type="text"
						name="visiting_flat"
						maxlength="100"
						required=""
						id="id_visiting_flat"
					/>
				</p>
				<p>
					<label for="id_visiting_date">Visiting date:</label>
					<input
						type="date"
						class="datepicker"
						name="visiting_date"
						required=""
						id="id_visiting_date"
					/>
				</p>
				<p>
					<label for="id_visiting_time">Visiting time:</label>
					<input
						type="time"
						name="visiting_time"
						required=""
						id="id_visiting_time"
					/>
				</p>
				<button
					type="submit"
					class="btn"
					style="background-color: blanchedalmond; color: brown"
				>
					Submit
				</button>
			</form>
		</div>
	</body>
</html>

main/templates/main/paidbill.html
{% extends "main/header.html" %} {% block content %}

<head>

    <meta charset="utf-8">

    <!-- Load paper.css for happy printing -->


    <!-- Set page size here: A5, A4 or A3 -->
    <!-- Set also "landscape" if you need -->
    <style>@page {
        size: A4 portrait;
        margin-top: 8px;
        margin-bottom: 10px;
        margin-left: 20px;
    }</style>
    <style>
        /* Three image containers (use 25% for four, and 50% for two, etc) */
        .column {
            float: left;
            padding: 5px;
        }

        /* Clear floats after image containers */
        .row::after {
            content: "";
            clear: both;
            display: table;
        }

        table tbody tr td {
            padding: 2px !important;
            line-height: 1.35 !important;
        }

        @media print {
            .box-body {
                margin-top: 10px !important;
                margin-bottom: 10px;
            }
        }
    </style>

    <script type="text/javascript">
      function printPageArea(areaID){
        var printContent = document.getElementById(areaID);
        var WinPrint = window.open('', '', 'width=900,height=650');
        WinPrint.document.write(printContent.innerHTML);
        WinPrint.document.close();
        WinPrint.focus();
        WinPrint.print();
        WinPrint.close();
    }
    </script>
    <style>
        .center-me {
            font-size: 15px;
            margin: auto;
            height: 10px;
            max-width: 500px;
            margin: 75px auto 40px auto;
            display: flex;
        }
    </style>
</head>
<!-- Set "A5", "A4" or "A3" for class name -->
<!-- Set also "landscape" if you need -->
<body class="A4 portrait">

<!-- Each sheet element should have the class "sheet" -->
<!-- "padding-**mm" is optional: you can set 10, 15, 20 or 25 -->
<section class="sheet" id="content-print">
    <style>
        table {
            /*border-collapse: unset !important;*/
        }
    </style>
<div id="printableArea">
    <div class="box-body" id="box_data" style="display: flex;padding: 5px 10px 0 10px;margin-bottom: -21px;">
        <div style="width: 100%;padding-right: 10px;" class="col-md-12">
            <div class="row">
                <div class="col-lg-4" style="width: 70%;padding-left: 20px;">
                    <h4 style="text-align:center;">MAINTENANCE BILL</h4>
                </div>

            </div>

            <br>




            <table width="100%" border="1">
                <tr style="background: rgba(217,225,242,1.0)">
                    <th class="text-center" colspan="2" style="width: 25%;">Bill To</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Name</th>
                    <th>{{profile.name}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Flat Number</th>
                    <th>{{profile.flat_no}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Email</th>
                    <th>{{profile.email}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Published</th>
                    <th>{{bill.publish_date}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Date Due</th>
                    <th>{{bill.due_date}}</th>
                </tr>
                <tr>
                    <th style="width: 5%;font-size: 12px;background: rgba(217,225,242,1.0)">Payment Time</th>
                    <th>{{bill.payment_time}}</th>
                </tr>
            </table>
            <br>
            <table width="100%" border="1px">
                <tr style="background: rgba(217,225,242,1.0);">
                    <th class="text-center">
                        Sr No.
                    </th>
                    <th class="text-center" colspan="3">
                        Particulars
                    </th>
                    <th class="text-center">
                        Amount
                    </th>
                </tr>
                <tbody>

                <tr><td>1</td><td colspan="3">Repairs and Maintenance Fund</td><td>{{bill.repairs_maintenance_charges}}</td></tr>
                <tr><td>2</td><td colspan="3">Society Service Charges</td><td>{{bill.society_service_charges}}</td></tr>
                <tr><td>3</td><td colspan="3">Parking Charges</td><td>{{bill.parking_charges}}</td></tr>
                <tr><td>4</td><td colspan="3">Sinking Fund</td><td>{{bill.sinking_fund_charges}}</td></tr>
                <tr><td>5</td><td colspan="3">Charity Fund</td><td>{{bill.charity_charges}}</td></tr>
                </tbody>



                <tfoot>
                <tr style="background: rgba(217,225,242,1.0);">
                    <td colspan="4">Total Amount</td>
                    <td colspan="1">{{total}}</td>
                </tr>
                
                </tfoot>


            </table>
            <br>

        </div>

    </div>
</div><br>
<!-- <a href="{% url 'main:pay' bill_id %}" class="btn">Pay</a> -->
<a href="javascript:void(0);" class="btn" onclick="printPageArea('printableArea')">Print</a><br><br>
</section>
</body>
<style media="screen">
  a.btn{
    position:relative;
    left:500px;
  }
  h4{
    position:relative;
    left:150px;
  }
</style>
{% endblock %}

main/templates/main/searchbill.html
{% extends "main/header1.html" %} 
{% block content %}
{% load static %}

  <body>
    <main class="layout layout--3">
      <div class="container">
        {% include 'main/includes/sidepanel.html' %}
        <div class="roomList__header" style=" 
        position: relative;
        right: 0px;">
<div style="margin:0; width: 900px">
  <h1 style="text-align: center"><span>Bill Box</span></h1><br/>
  <!-- for due bills -->
  {% if due %}
  <h1 style="text-align: center">Due Bills</h1><br>
  <div class="roomList__header" style="">
   
    <div class="row">
      {% for b in due reversed %}
      <div
        class="col s12 m6 l4"
        style="
          width: 250px;
          float: left;
          margin: 0 20px 20px;
          background-color: #3f4156;
          text-align: center;
          border-radius: 20px;
          padding: 30px;
        "
      >
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">Maintenance Bill</span>
            <p>Bill ID: {{b.bill_id}}</p>
            <p>Published Date: {{b.publish_date}}</p>
            <p>Due Date: {{b.due_date}}</p>
          </div>
          <div class="card-action">
            <a href="{% url 'main:viewbill' b.id %}">View</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
    {% endif %}
    <!-- end due bills -->

    <!-- for pending bills -->
    {% if pending %}
    <h1 style="text-align: center">Pending Bills</h1><br>
    <div class="roomList__header" style="">
    
      <div class="row">
        {% for b in pending reversed %}
        <div
          class="col s12 m6 l4"
          style="
          width: 250px;
          float: left;
          margin: 0 20px 20px;
          background-color: #3f4156;
          text-align: center;
          border-radius: 20px;
          padding: 30px;
          "
        >
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Maintenance Bill</span>
              <p>Bill ID: {{b.bill_id}}</p>
              <p>Published Date: {{b.publish_date}}</p>
              <p>Due Date: {{b.due_date}}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'main:viewbill' b.id %}">View</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

    {% endif %}
    <!-- end pending -->

    <!-- show paid bills -->
    
    {% if paid %}
    <h1 style="text-align: center">Paid Bills</h1><br>
    <div class="roomList__header" style="height:auto;">
      
      
      
        {% for b in paid reversed %}
        <div
          class="col s12 m6 l4"
          style="
          width: 250px;
          float: left;
          margin: 0 20px 20px;
          background-color: #3f4156;
          text-align: center;
          border-radius: 20px;
          padding: 30px;
          "
        >
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Maintenance Bill</span>
              <p>Bill ID: {{b.bill_id}}</p>
              <p>Published Date: {{b.publish_date}}</p>
              <p>Due Date: {{b.due_date}}</p>
              <p>Payment Time: {{b.payment_time}}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'main:viewbill' b.id %}">View</a>
            </div>
          </div>
        </div>
        {% endfor %}
    
     
    </div>

    {% endif %}
    <!-- end paid bills -->
  
</div></main>
<script src="script.js"></script>
</body>
</html>

{% endblock %}  

main/templates/main/service.html
{% extends "main/header1.html" %} 
{% block content %}
{% load static %}

<body>
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="/">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Service Request</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="post">{% csrf_token %}
            <div class="form__group">
              <label for="room_name">Service Name</label>
                  <select class="browser-default" name="service_name" id="id_service_name">
                    <option value="1">Electrician</option>
                    <option value="2">Internet Service Provider</option>
                    <option value="3">Plumber</option>
                  </select>
              </datalist>
            </div>

            <!-- <div class="form__group">
              <label for="room_topic">Flat no. to be extra sure</label>
              <input required type="text" name="client"/>
            </div> -->


            <div class="form__group">
              <label for="room_about" >Specify your request:</label>
              <textarea name="service_details" required id="room_about" placeholder="Write in detail about your request..."></textarea>
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="/">Cancel</a>
              <button class="btn btn--main" type="submit">Create Request</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
  {% endblock %}